CREATE TABLE ` USER ` (
`USER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'User unique code',
` NAME ` VARCHAR (100) NOT NULL COMMENT 'User full name',
`EMAIL` VARCHAR (255) NULL COMMENT 'User email address',
`USERNAME` VARCHAR (255) NOT NULL COMMENT 'Username of the user',
` PASSWORD ` VARCHAR (255) NOT NULL COMMENT 'Password of the user',
`SALT` VARCHAR (255) NOT NULL COMMENT 'Password SALT of the user',
`STATUS` CHAR (1) NOT NULL DEFAULT 'A' COMMENT 'Status of the record',
`DATE_CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date of the user was created',
`DATE_UPDATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date of the last updated',
PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `USER_ACCESS` (
`USER_ACCESS_ID` INT UNSIGNED NOT NULL COMMENT 'Unique code of user`s access',
`USER_ID` INT UNSIGNED NOT NULL COMMENT 'Unique code of user',
` DATE ` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date of connection',
`IP` VARCHAR (255) NOT NULL COMMENT 'IP of user',
` TYPE ` CHAR (1) NOT NULL DEFAULT 'C' COMMENT 'Stage of the connection',
PRIMARY KEY (`USER_ACCESS_ID`),
CONSTRAINT `FK_USER_ACCESS_USER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES ` USER ` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
INDEX `IDX_USER_ACCESS_USER_ID` (`USER_ID` ASC )
);


